exclude = [
    "__pycache__",
    ".git",
    ".pytest_cache",
    ".idea",
]
line-length = 120

[lint]
select = ["E2", "E3", "E4", "E5", "E7", "E9", "N8", "D1", "D2", "D3", "D4", "C90", "F", "B", "Q"]

[lint.mccabe]
max-complexity = 10
